services:
  postgres:
    image: postgres:15-alpine
    container_name: labsync_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: WbijamNaBombsiteA
      POSTGRES_DB: LabSyncDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: